[package]
name = "ahqrt"
version = "0.1.0"
edition = "2024"

[dependencies]
libc = { path = "./libc" }
# real_libc = { package = "libc", version = "=0.2.177" }

[target.'cfg(windows)'.dependencies]
windows = { version = "^0.62", features = [
  "Win32_Security",
  "Win32_System_Threading",
] }
